### ISSUE TITLE
Widget missing, FF 40

### ISSUE THREAD

**Issue by fraxen** [saikocat/firefox-fontdpi#3]
This has worked fine for me up until the last few versions, now the widget is missing, and I can't seem to find any way to activate it.

**Comment by saikocat** [comment]
They changed the addon API quite a bit for the past 5+ versions of Firefox (no status bar, .etc). I am quite caught up with work in real life. So I can't find much bandwidth right now to fix or rewrite it. No promise but I will try take a quick look tomorrow. Really sorry >.<

**Comment by saikocat** [comment]
Okay, I took a look. Not too difficult to edit. Probably will burn tonight to fix this. Thanks for bringing it up. I will try to get it done by tomorrow and publish it.

**Comment by saikocat** [comment]
<img width="460" alt="screen shot 2015-10-14 at 10 03 11 am" src="https://cloud.githubusercontent.com/assets/4039693/10473915/0aab1e40-725b-11e5-8f9d-7d9e86904d4c.png">
Here is the Updated UI

**Comment by fraxen** [comment]
Excellent, thanks!

**Comment by fraxen** [comment]
Is this pushed to the add-on repository? (is it pending review or something)
I don't mind installing this add-on from github, by I am not sure how to build an .xpi out of the repo!

**Comment by saikocat** [comment]
I already pushed the add-on. It is under reviewed now (76 position in the queue). I think you can still install the experiment version 0.2.0 in here https://addons.mozilla.org/en-US/firefox/addon/fontdpi/versions/ though (exact at https://addons.mozilla.org/firefox/downloads/file/360316/fontdpi-0.2.0-fx.xpi). If you can't access, let me know, I will send you the .xpi. Cheers!

**Comment by fraxen** [comment]
That worked very well, thanks! (I tried the latter link)
